__tests__/base.js
immer.js

Fixes #12 
Add an extra check to isProxy method to handle undefined value

make isProxy method check if value parameter is defined

---

immer.js

Avoid unexpected token error from babel compiler

Remove trailing comma in console.warn

---

__tests__/base.js
__tests__/frozen.js
changelog.md
immer.js
package.json
yarn.lock

Fix reflection on proxies

---

readme.md

Hello,
The changes relate to the issue #7. 
For the CDN part, I only added the unpkg one. For cdnjs the package needs to be registered. I can fill the request to register the package if you want.

Add travis, prettier and npm badges. Also add unpkg cdn

---

src/index.js

I think that the function is expressed explicitly. What do you think??

variable explicitly

---

src/immer.js.flow

Adds a Flow annotation, and provides name for the default exported function to fix errors with Flow type checking.

Improve Flow type definition file (Fixes #80)

---

readme.md

I think the difference would be more clear with such example.

Set state example correction

---

readme.md

Add a missing parenthesis in a code example.

Fix missing parenthesis in code example

---

readme.md

Everyone likes badges so I added some more.
These are kept in sync with npm.
Also I added a link to the JSDelivr CDN which includes some stats on usage.
See https://cdn.jsdelivr.net/npm/immer/

Add badges for npm and gzip size

---

readme.md

and check my own understanding :)

fix readme example

---

src/proxy.js

Changes the wording on two error messages in proxy.js

Better Error Messages in Proxy

---

readme.md

It's pedantic, but I can't help myself ever since [@StealthMountain](https://twitter.com/stealthmountain).

Fix typo in README.md

---

__tests__/null-base.js

Reproducing issue #148.

---

__performance_tests__/add-data.js
__performance_tests__/measure.js
__performance_tests__/todo.js
package.json
yarn.lock

had to reduce `MAX` by a factor of 10 so it could complete

added seamless-immutable to performance tests

---

__performance_tests__/incremental.js

Add incremental benchmark

---

changelog.md

remove extraneous word from changelog for 1.7.2

---

__tests__/base.js
__tests__/frozen.js
src/common.js

Closes #229 
This passes the tests added by a60a6fa08f0015ca66d8e3161a8197982fdba417
@mweststrate Is this considered breaking?

fix: never auto-freeze new objects

---

__tests__/base.js

Add tests for nested `produce` calls with draft objects. Previously, only non-drafts were tested.

fix(tests): nested produce calls

---

.travis.yml
package.json

Sorry for letting this get through! ❤️ 
Closes #264

fix(ci): build before release

---

__tests__/types.ts
package.json
readme.md
src/immer.d.ts
yarn.lock

fix: improve .ts tests and avoid clobbering object properties of interfaces

---

src/immer.d.ts

fix(ts): produce function

---

readme.md

This is my library mentioned over in #289. Everyone I've shown it to has liked what they've seen and it got a [spontaneous shout-out on reddit](https://www.reddit.com/r/typescript/comments/ai20s1/reduxtsutils_stumbled_upon_this_library_it_seems/).

docs: add redux-ts-utils to "cool things made with immer"

---

__tests__/patch.js
src/patches.js

Fix for https://github.com/mweststrate/immer/issues/319

Array patches were optimized

---

__tests__/base.js
src/es5.js

fix(es5): delete then set an existing property

---

bili.config.ts
package.json

fix(build): use .module.js instead of .mjs for esm bundle, closes #331

---

src/common.js

Just added a  && System.for check to prevent immer to  brake on IE11

Added check for Symbol.for for IE11 compatibility

---

readme.md

add redux-immer to "Cool things built with immer"

add redux-immer to "Cool things built with immer"

---

__tests__/curry.js
__tests__/readme.js
readme.md
src/immer.d.ts
src/immer.js
src/index.js

feat: introduced produceWithPatches. Implements #400

---

__tests__/readme.js
_site/readme/index.html
docs/api.md
docs/performance.md
docs/support.md

It's awesome, in simple words. I've gone through all the docs and it's pretty fine now. Just a few typos, now fixed

fix grammatical errors and typos

---

docs/installation.md

The adverb form makes more sense here

Fixes word form in docs/installation.md

---

__tests__/base.js
__tests__/polyfills.js
__tests__/tsconfig.json
package.json
src/common.ts
src/es5.ts
src/finalize.ts
src/immer.ts
src/map.ts
src/patches.ts
src/proxy.ts
src/scope.ts
src/set.ts
src/types.ts
tsconfig.json
yarn.lock

Code cleanup

---

docs/pitfalls.md

Include note about exotic objects not being supported #504

---

docs/resources.md

I wrote an article describing how we use Immer to implement undo/redo functionality on production. I thought it might be useful to others. Please feel free to close it if you think it's not adding value to the doc.

Added undo-redo guide to external resources

---

package.json
yarn.lock

Switch to https://github.com/bcomnes/cpx2
Resolves #563

Switch to maintained fork of cpx

---

__tests__/flow/.flowconfig
__tests__/flow/flow.js.flow
package.json
src/types/index.js.flow
yarn.lock

- Draft parameter can be undefined (unless type annotation is provided).
- Not possible to return undefined.

[Flow] Fix two issues with curried produce

---

__tests__/base.js
__tests__/map-set.js
src/plugins/mapset.ts

Map: new map key not added if value is undefined

---

__tests__/patch.js
src/plugins/patches.ts
src/utils/errors.ts

Details: SNYK-JS-IMMER-1019369 / CVE-2020-28477
https://snyk.io/vuln/SNYK-JS-IMMER-1019369

fix: Fixed security issue #738 when applying patches

---

docs/example-reducer.md
src/types/index.js.flow

Fix typo at docs and Flow declaration file

---

src/utils/common.ts

https://github.com/immerjs/immer/issues/766

fix isPlainObject to support cross frames

---

website/docs/introduction.md

Very minor change, but it bothered me a bit :)
- well know -> well-known

docs: fix adjective

---

readme.md

| --- | screenshot |
|:--:|:---:|
| before |  <img width="750" src="https://user-images.githubusercontent.com/14012511/233770761-8f487f9a-0b68-4ee5-847c-084a3eb098db.png">  |
| after | <img width="750" src="https://user-images.githubusercontent.com/14012511/233770827-60826fd6-2ebf-40b7-8125-c28bd9d4a1ca.png">  |
cc @mweststrate

chore: update badge
