immerjs/immer

__tests__/base.js, immer.js
1. Using a revocable proxy instead of a proxy, we invalidate the proxy when immer function executes
1. I used jsdoc @typedef, but I can create an internal typescript definition file and reference it in immer. js if needed
Fixes #10
=> invalidate the proxy of the base state after immer function executes

package.json
This is needed in order to have the definition file included when immer is packaged
Fixes #18
=> Add index.d.ts in package.json `files` attribute

__tests__/base.js, __tests__/performance.js, es5.js, immer-es5.js, immer.js, package.json, readme.md
Fixes #8 
First implementation is promising and feature complete! Needs some clean up, feature detection etc. Performance is quite neat so far (but bare in mind that the Proxy impl is not yet optimized, while the non-proxy impl is)
The update-10k-todos-in-a-set-of-100K benchmark: 
```
✓ just mutate (2ms)
✓ deepclone, then mutate (475ms)
✓ handcrafted reducer (15ms)
✓ immutableJS (65ms)
✓ immer - with autofreeze (309ms)    // Immer, with auto freeze enabled
✓ immer - without autofreeze (148ms) // Immer, but without auto freeze enabled
✓ immer - NO PROXIES - with autofreeze (470ms)
✓ immer - NO PROXIES - without autofreeze (428ms)
```
=> Don't require proxies for a correct working

package.json
es5.js is not included when installing immer 0.2.0 from npmjs :
```sh
ll node_modules/immer
total 76
drwxr-xr-x   2 nico users  4096  4 janv. 01:32 .
drwxr-xr-x 751 nico users 36864  4 janv. 01:33 ..
-rw-r--r--   1 nico users  1836  4 janv. 01:32 changelog.md
-rw-r--r--   1 nico users  7725  4 janv. 01:32 immer.js
-rw-r--r--   1 nico users   970  4 janv. 01:32 index.d.ts
-rw-r--r--   1 nico users  1074  4 janv. 01:32 LICENSE
-rw-r--r--   1 nico users  1261  4 janv. 01:32 package.json
-rw-r--r--   1 nico users  7346  4 janv. 01:32 readme.md
```
=> Include es5.js in npm publish

index.d.ts
Change the definition of `setAutoFreeze` to avoid typescript with `"noImplicitAny": true,` options to throw an Error.
=> explicit return of setAutoFreeze

__tests__/base.js, src/es5.js, src/proxy.js
I got error on this test case. (see the diff)
I could not figure out why this is caused.
It seems some copy of array element is a Proxy.
Therefore, I did finalizing copy on `finalizeArray` in any case.
I don't know the same thing is needed on `finalizeObject`.
Would you review my code please?
I'm very glad to meet such a wonderful library :)
**addition**
I found another case below:
```
const base = {
arr: [{count: 1}, {count: 2}]
}
const result = produce(base, draft => {
draft.arr = [
draft.arr[1]
]
draft.arr[0].count = 1
})
expect(result).toEqual({
arr: [{count: 1}]
})
```
This also causes an error.
Shouldn't I use the draft object on new array or object....?
=> Fixed finalizing array

__tests__/base.js, src/proxy.js
I fixed a problem on using constructor for proxy of an array.
It is caused because `'constructor' in state.proxies` always become `true`.
=> Fixed treating constructor on proxy

src/es5.js, src/proxy.js
`freeze` seems not be used anywhere in these two files.
=> Remove unused import

__tests__/curry.js, readme.md, src/immer.d.ts, src/immer.js, src/immer.js.flow
Should implement issue #111.
Notes:
- If a function is given both for `fn` and `initialState`, `produce(fn, initialState)` will throw an error, see https://github.com/pkerschbaum/immer/blob/202d54cb96949b45cdfdfb08f180b93723faef29/src/immer.js#L24.
Because if produce would allow this, each call of the curried function with `undefined` would create a curried function again.
- The typings should be improved because currently, `S` is typed with `any`, and if two arguments are passed to `produce`, TypeScript (and I think also Flow) cannot exactly determine which overloaded version of the function gets called.
If we add typings for the state/currentState/initialState `S`, the typing systems should be able to distinguish the `produce` calls.
=> resolve #111: allow passing initial state to curried producer function

src/common.js
Object.assign() is not available in IE11. In environments without polyfills this library crashes on IE. This PR replaces it with a for-in loop.
=> Replace Object.assign in common, since it's not supported in IE

__tests__/base.js, src/immer.js
This PR adds a spec for #148. and fixes it. 
When the `baseState` is a primitive value or `null`, immer takes a shortcut and doesn't proxy. But it must still check if the producer returns `undefined`, and if yes, return the `baseState`.
=> Fix #148: default returned value

__tests__/base.js
There is a test that doesn't run because of a typo: "if(...)" instead of it(...)". This hides other issues in the test.
This PR fixes the typo and also the actual test.
=> Fix: Base test uses "if(...)" instead of it(...)"

readme.md
Of course after #161 was merged I realized that my README example didn't actually do anything. This just makes sure that the original state is passed as the first parameter. Previously `newState` would have been a function instead of the new state object.
=> Fix TypeScript example

__tests__/flow/flow.js.flow, __tests__/flow/ts.ts, __tests__/original.js, readme.md, src/common.js, src/immer.d.ts, src/immer.js, src/immer.js.flow
This addresses #153 and exposes an `original` function, useful for `===` comparing a proxy with an original object. The docs / tests should explain most of the implementation!
=> Add an original function

readme.md
0. Fix typo on `inde\` => `index: `
1. Remove extra semicolons from obj initialization. To keep it consistent with the other examples and closer to valid js, it's updated.
=> readme: consistent formatting in examples

readme.md
=> fixed development

__tests__/flow/ts.ts, __tests__/types.ts, package.json, src/immer.d.ts, src/patches.js, src/proxy.js, yarn.lock
Later versions of Prettier support TypeScript.
This PR upgrades Prettier to the latest version and enables it on TypeScript code.
=> Upgrade prettier and enable prettier on TypeScript code

src/immer.js
Babel spits out the following:
```js
return function () {
for (var _len = arguments.length, args = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
args[_key - 1] = arguments[_key];
}
var currentState = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : initialState;
return produce(currentState, function (draft) {
return recipe.call.apply(recipe, [draft, draft].concat(args));
});
};
```
*edit:* I haven't run the perf tests yet.
WDYT?
=> simplify curried producer impl

.travis.yml
Using the Yarn cache can speed up the builds significantly.
=> ci: use yarn cache

__tests__/base.js, __tests__/curry.js, src/immer.js
Currently, the first 2 arguments of `produce` cannot both be a function. Otherwise, an error is thrown.
Instead of throwing an error, the `produce(baseState, recipe)` code path should be taken, which would let users use functions as a base state. This goes really well with #236, because it lets us guarantee to callers that _any value_ can be used as the base state of a `produce` call.
You _cannot_ use a function as the `initialState` of a `produce(recipe, initialState)` call (also known as: a curried producer).
=> fix(produce): never curry when 2nd argument is a function

__tests__/base.js, __tests__/curry.js, src/immer.js
Fixes #233 
I'm thinking this is a breaking change, since someone may be relying on an error being thrown in some weird situation.
=> fix(produce): avoid throwing on unproxyable objects

src/es5.js
The `shallowEquals` function you took from `fbjs` had a branch that wasn't used by Immer, so I merged it into `hasObjectChanges` and even optimized it. :)
=> simplify es5 object key diffing

src/es5.js
This patch only applies to `produce` calls that have a patch listener.
- Removed the `diffKeys` function, which created 2 avoidable arrays.
Now, the keys are diffed and processed in one pass.
- For objects, the last loop over `proxy` has been removed.
- Added fast paths for pre-existing keys when looking for added/removed
object keys.
- Avoid passing removed array values to `markChangesRecursively`.
- Unwrap `state.assigned` as a local variable for fast access.
=> perf: es5 markChangesRecursively

src/proxy.js
Optimize based on value's truthiness. Truthy values are guaranteed to never be undefined, so we can avoid the `in` operator. Lastly, truthy values may be proxies, but falsy values are never proxies.
=> perf: proxy assign

readme.md
=> Add immer-reducer

__tests__/base.js, __tests__/patch.js, __tests__/polyfills.js, __tests__/produce.ts, src/common.js, src/es5.js, src/immer.d.ts, src/immer.js, src/index.js, src/patches.js, src/proxy.js
When a class instance has the new `immerable` symbol in its own properties, its prototype, or on its constructor, the class instance can be drafted.
When drafted, class instances are basically plain objects, just with a different prototype. No magic here.
The main commit: https://github.com/mweststrate/immer/commit/be4898274f4da505849b4dda1abcd9e8bd035a4b
- Allow symbols as property names in drafts
- Add non-enumerable property support to drafts
- Improved error messages
- Fixed issue where ES5 drafts were not being marked as `finalizing` before being shallow cloned, which resulted in unnecessary draft creation
=> feat: limited class support

__tests__/__snapshots__/manual.js.snap, __tests__/base.js, __tests__/manual.js, __tests__/produce.ts, readme.md, src/es5.js, src/immer.d.ts, src/immer.js, src/immer.js.flow, src/index.js, src/proxy.js, src/scope.js
Localized branch of #305, implements #302 
Remaining work:
=> Async recipes

src/common.js
This uses `Symbol.for` when creating the `DRAFTABLE` and `DRAFT_STATE` symbols, so that separate installations of Immer can work together.
**Note:** The `nothing` symbol is still not portable across installations, since it never escapes any producer that returns it. The only reason this could be an issue is if an Immer-using library transparently wraps a user's function and asks them to install their own copy of Immer if they want to return `nothing` (in that case, the library should instead re-export `nothing` for its users).
This repro shows this PR working as expected:
https://github.com/aleclarson/repro/tree/portable-immer
Fixes #322
=> fix: share internal symbols between immer installations

src/immer.d.ts
I noticed that `@types/lodash` uses this declaration for ES5 compatibility.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6a5529e838d9386fb6567296e84d945e25805281/types/lodash/index.d.ts#L37-L47
Fixes #321
=> fix(ts): --target=es5 compatibility

readme.md
With React Native 0.59 release - they upgraded the Android JSC so I think this polyfill is no longer needed - https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md
I might be wrong here, can someone else confirm please?
=> I think RN 0.59 no longer needs Proxy polyfill on Android

package.json
Immer already has a UMD build, which is great! This PR adds jsdelivr and unpkg fields in package.json pointing to the same place, so jsdelivr.com and unpkg.com respectively can automatically serve the right files, and AMD implementations that depend on one or both of those (like d3-require) can automatically load immer directly or as a dependency.
=> Add unpkg and jsdelivr fields to package.json

readme.md
Just realized that immer-reducer works with the React useReducer hook just fine because it is just a reducer generation lib and no deps with Redux whatsoever.
https://github.com/epeli/immer-reducer#-react-hooks
=> immer-reducer works with React useReducer hook too

readme.md
All the other examples in the readme import the demonstrated immer export except `original`.  Added import for `original` example.
=> Include import statement in `original` example

__tests__/patch.js, src/immer.js, src/patches.js, src/proxy.js
Fixed an issue where adding and then deleting a property generated the wrong patches; in Proxy implementation, it generated an `add` patch with value `undefined`. 
Fixed an issue where replaying patches on a draft in a producer, where in the middle there was an 'entire state replacement' patch, this new state could not be returned, as both the draft would be modified and a new state would be returned. Nice benefit of this fix is that any patch before a replacement won't even be replayed.
=> Several fixes to patch generation

__tests__/patch.js, src/patches.js
In the original `applyPatches`  implementation, in the `replace` and `add` switch cases, new values are assigned using `base[key] = patch.value`. 
In this way, if the values are objects, then they are assigned by reference. 
Later `applyPatches` operations may change the assigned values, and hence the value fields in the patches will also be modified.
I modified the `applyPatches` implementation and added an additional new test case.
=> fix: ensure patches are reusable

__tests__/patch.js, src/patches.js
Fixes #208
Please look for things I haven't tested. I found the part of the code that I was reading very hard to understand due to the lack of descriptive names and unexpected swapping of those variable names that I did understand (see https://github.com/immerjs/immer/blob/master/src/patches.js#L15). For this reason I am not sure that I have not introduced unexpected behavior.
=> feat: Always use remove command in generateArrayPatches()

__tests__/frozen.js, readme.md, src/common.js, src/immer.js
=> BREAKING CHANGE: In development mode, any new value stored in a tree will be deeply frozen

docs/freezing.md
Hi Immer maintainers,
Just a small drive-by docs fix! This PR clarifies the default freezing behavior by removing one of the conflicting descriptions.
Thanks,
xkxx
=> Docs: remove conflicting desc. of default freezing behavior

src/immer.js
Some older browsers including Firefox 24 have support for `Proxy`, but not `Proxy.revocable`. This ensures that we fall back on the legacy browser behavior when `Proxy.revocable` is missing.
=> Use legacy proxies if Proxy.revocable is not defined. Fixes #435

src/patches.js
I noticed this errant import while working on this repo locally. It looks like it causes rollup/bili warnings. 
```
warning circular_dependency: Circular dependency: src/immer.js -> src/patches.js -> src/immer.js
warning non_existent_export: Non-existent export 'createDraft' is imported from src/immer.js
```
=> remove non-existent import

.travis.yml, __tests__/__snapshots__/hooks.js.snap, __tests__/base.js, __tests__/hooks.js, __tests__/patch.js, src/common.js, src/es5.js, src/proxy.js
Hi guys! This is a draft solution for es5 map support. What do you think about this approach? 
It should works with babel preset, also it may works in IE11 ;) 
Now `map draft` tests passes and I'm planning to add Set support, patches, etc
=> es5 support for Map/Set

__tests__/__snapshots__/manual.js.snap, __tests__/curry.js, __tests__/frozen.js, __tests__/manual.js, src/proxy.js
This PR fixes #472, which in cases `Map`s throw. The problem that the test was pass before fix, even though in [the browser](https://codesandbox.io/s/icy-frog-flbdu) it would throw, not sure why.
Also, even tough it fixes the issue, I'm not sure this the root of problem. This solution might be only a patch.
Help is welcome in navigating Immer
=> Fixing #472 (In proxy, Freezed Maps don't become draft)

tsconfig.json
Fixes #489 by enabling sourcemaps in tsconfig.json. 
While we're in the neighborhood, this PR also enables declaration maps, which are auto-generated sourcemaps for .d.ts files. Declaration maps enable the "Go To Definition" (F12) feature of VSCode, CodeSandbox, and other IDEs to navigate to the actual immer implementation code. Without declaration maps, the user only can only navigate to the .d.ts file when "Go To Definition" is used.
=> build: Enable sourcemaps and declaration maps in tsconfig.json

__tests__/patch.js, src/es5.ts
May be it's about two points:
1. The length is the same, `markChangesRecursively` is still necessary for un-processed array items. such as delete property in an object array, the `nextState` could be correct, but `patches` not works as expected.
2. The `delta` item has been process as `add`/`remove`. The remaining items count would be the `min` value.
=> fix: patches when delete object property in array

__tests__/draft.ts, docs/typescript.md
The function is called castDraft, the `asDraft` version seems to be a remnant of an earlier name. It’s only present in the documentation and the test titles, so this change is non-functional.
=> fix: consistent naming for castDraft, fixup 2d27f33f6

docs/pitfalls.md
We've come across this particular issue and didn't find it in the pitfalls section, so it took some more investigation and reading all articles on the page to find the answer, classes.
However, I think it's somewhat common to use classes, and with this, people will encounter unexpected behavior, hence Pitfalls section.
=> Add section about using classes with immer

docs/built-with.md
Redux Starter Kit has been renamed to Redux Toolkit.
=> Docs: Update redux-starter-kit to redux-toolkit

__tests__/__prod_snapshots__/base.js.snap, __tests__/__prod_snapshots__/curry.js.snap, __tests__/__prod_snapshots__/frozen.js.snap, __tests__/__prod_snapshots__/manual.js.snap, __tests__/__prod_snapshots__/patch.js.snap, __tests__/__prod_snapshots__/plugins.js.snap, __tests__/__prod_snapshots__/readme.js.snap, src/utils/errors.ts
As [issue#550](https://github.com/immerjs/immer/issues/550) said
[https://bit.ly/38PiBHb](https://bit.ly/38PiBHb) is not valid any more.
This PR just change url older to new one.
The new url origin url is `https://github.com/immerjs/immer/blob/master/src/utils/errors.ts`.
Shorten url is [https://bit.ly/3cXEKWf](https://bit.ly/3cXEKWf)
That's it.
=> fix: change Full error url (issue#550)

__tests__/patch.js, src/plugins/patches.ts
When you are generating patches in a nested reducer, patches values can be a Proxy. They need to be cloned before stored into the patch otherwise the patch cannot be applied as the proxy will be revoked.
I added a single test for this and ensured it was failing before my patch. If you want other tests to be added, please tell me what you would like.
Fixes #559
=> Ensure values in patches are never a draft

docs/performance.md
I think there is a typo: skeeping should be skip.
=> Update performance.md - Fix a possible typo

docs/api.md
Simply remove a double "the the" in the API docs.
=> docs: fix typo

src/types/types-external.ts
Should fix  #657 
Extracting anonymous type from Drat type declaration into a named type helps typescript to produce smaller .d.ts files for projects with Immer and thereby work faster.
=> Replace anonymous type in recursive Draft declaration for better tsc performance in watch mode.

__tests__/regressions.js, src/utils/common.ts
This small PR addresses an error that occurs when working with immer and seamless-immutable in one project. See #650.
=> fix: use Array.prototype.slice() for copying arrays. Fixes #650

__tests__/map-set.js, src/plugins/mapset.ts
=> set assigned keys when clear map

docs/performance.md
Found a typo in performance.md
cool => call `Object.freeze`
Please correct me if im merging to the wrong branch
=> Typo in performance.md

docs/complex-objects.md
The time getter is trying to accessing `this.minutes`, but it's missing `this.`!
```ts
get time() {
return `${this.hour}:${minute}`
}
```
=> Fix Clock time getter in complex objects docs

src/types/types-external.ts
This should fix #624 .
Instead of my initial idea of providing interfaces with the same shape as `ReadonlyMap`, `ReadonlySet`, `WeakMap` and `WeakSet` (which would also have worked, but probably required a lot more duplicate code), this is now following a different approach:
It checks if the types are `any` (which they would fall back to if they were not present) or a keyless interface (which at least `ReadonlyMap` and `ReadonlySet` would be if the `node` types are installed), in which case they fall back to `void`, which does not trigger the conditional.
The check for `any` is done by `true | false extends (T extends never ? true : false)` -  every other type will either be `true` or `false`, but since `any` takes both paths, it becomes `true | false`.
The check for the empty interface …
=> skip ReadonlyMap and ReadonlySet types when not available

src/immer.ts
Update comments to avoid misleading developers to troubleshoot bug
=> fix: update comments

__tests__/patch.js
I noticed that one of the tests failed when run locally (I am in the CET timezone ATM), because the stringified date did not match the snapshot (was 1 hour off):
This probably stems from the fact that the `Date` constructor parses the values as though they were in the local timezone (CET +1 for me). Going back to UTC (which is what `toJSON` produces) subtracts that 1 hour, which makes it show 7:08:08 instead of 8:08:08.
I reckon using a UTC string could solve the problem. Another alternative would be using a constructor with a UNIX timestamp, but I reckon the current solution is more readable.
Fixes #712
=> Use UTC date string in tests to be timezone independent

docs/built-with.md
NPM package: https://www.npmjs.com/package/cool-store
=> docs: add cool-store into built-with.md

docs/pitfalls.md
Add a section about referential equality to pitfalls, with the simple 
example of using `indexOf` on a draft array to match an element.
Fixes #730
=> Add referential equality to pitfalls

__tests__/manual.js
There was a deprecation warning because `new Buffer([])` was used in one of the tests.
```
(node:25795) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS  __tests__/manual.js
```
=> chore: fix Buffer deprecation warning in test

docs/introduction.md
In the docs, I noticed there is an assumption in the example about the assistant's gender. This diff changes the text.
I had a version using "they" but when reading that back I was worried that non-native English speakers may get confused in this particular example since it is very early on in the docs and the example itself only serves as an elaboration of how draft state works. The version in this PR has the most clarity in my opinion, but I know that can be subjective. Happy to change it!
=> Gender neutral language in the docs

website/docs/example-reducer.mdx
First off I love this package and appreciate everyone's work on it 🎉 
I get that there's only one `case` here and you want to have as few lines as possible but for people plucking this example and then using it to build out their own reducer, they'll immediately [run into issues][1] as soon as they add a second `case` with no `break` in the first. Given that many of your readers may be beginners, it seems safer to include.
[1]: https://stackoverflow.com/questions/8563970/switch-without-break
=> docs: add `break` to `switch` block

website/docs/installation.mdx
new Hermes which is available on React Native 0.64 support proxy.
=> update Doc: new Hermes support proxy 👏

src/utils/common.ts
Fixes https://github.com/immerjs/immer/issues/804
=> perf: isPlainObject: add quick comparison between input and `Object` to short-circuit taxing `Function.toString` invocations

src/core/current.ts, src/core/finalize.ts, src/core/proxy.ts, src/core/scope.ts, src/plugins/es5.ts, src/plugins/mapset.ts, src/plugins/patches.ts, src/types/types-internal.ts, src/utils/common.ts, src/utils/plugins.ts
hi, @mweststrate , thank you for great tool.  i review the code and got a  commit https://github.com/immerjs/immer/commit/fdc78db0ba08a68899722b2d32261207205bad95 which just for reduce bundle size . yes?
And [typescript const enum](https://www.typescriptlang.org/play?ts=3.9.7#code/MYewdgzgLgBApmArgWxgBQE4gB4E8AquADnDAN4BQAkJjrgPIBGAVnMLALwwCcANNbTwBBDBgCGuflQCiAZQCsTVuxhcADFLnyR4ydQCyYolNlwoFAL4UKAGzMwIq9FjyESAOlNQA3EA) may be  a better way for code and reduce ?
=> reduce size by ts const enum

src/core/immerClass.ts
applyPatches should specify its input as type `T` so that TypeScript can better infer the correct `T` for its output.
Fixes #809
=> Better applyPatches type

website/docs/example-setstate.mdx
Moved id generation for new todos out of reducers to keep them pure.
The main behind this PR is, that reducers should be pure functions. And it would be great if docs of other libs also don't violate this rule in their examples.
=> doc: update example-setstate.mdx

__tests__/patch.js, src/core/immerClass.ts, src/plugins/patches.ts
Closes #871
It's actually amazing '-' was doing anything at all! Definitely a JS quirk that the first argument to `splice` is coerced to a number, effectively becoming 0 if the parameter can't be parsed.
I also dropped an unnecessary `any` cast, and added a check for avoiding an unnecessary copy of the patch array.
=> Append to array when key is "-"

website/docusaurus.config.js, website/src/css/immer-infima.css
This PR fixes the mobile navbar menu styles. The mobile navbar menu was essentially unusable with the light theme and inconsistent with the navbar for the dark theme.
=> docs: fix mobile navbar menu styles

__tests__/base.js, src/core/immerClass.ts
Fixes `produce` and `produceWithPatches` behaving differently when passed an async recipe. `produceWithPatches` returns:
```javascript
[ Promise { <pending> }, undefined, undefined ]
```
instead of a promise of `[nextState, patches, inversePatches]`
=> async produceWithPatches

package.json
This pull request fixes #901 by publishing the ES module with the `.mjs` file extension.
For now, the existing ESM bundle `dist/immer.esm.js` is simply copied to `dist/immer.esm.mjs` building. This makes sure that there are no breaking changes, just in case any library includes the old file manually. In the next major release of Immer, the old bundle can be removed. By then jaredpalmer/tsdx#1059 might be released, which I believe will adapt the bundle file extensions.
This pull request also adds an `exports` field to `package.json`, which will make sure that Node.js will import the ES module when run in ESM mode. The wildcard export `"./*": "./*"` will make sure that any sub paths can be continued to be imported (for example something like `import 'immer/src/immer.ts'`, which makes this a …
=> fix: Fix importing ES module from Node.js (#901)

website/docs/produce.mdx
The current format was linking to https://immerjs.github.io/immer/produce/return , which does not exist.
*Disclaimer: I'm not actually sure how to build/host/test these docs myself, but I based this change off of the changes in https://github.com/immerjs/immer/commit/bc359167ec53759f981f503a16a19a5e9a810159*
=> Fix link to `return` on `produce` doc page

website/docs/produce.mdx
`produce` function operates on `baseState` and produces `nextState`. Everywhere in this docs original state called `baseState`, but in the first snippet it's called `currentState`. I'm renaming it for consistency.
=> docs: Update produce/mdx

src/types/types-external.ts
👋 Hello, it looks to be a long standing definition but this line seems to be incorrect. 
For reference:
=> fix: incorrect return type for async produceWithPatches

src/types/types-external.ts
I believe this should be consistent with `produce` on lines [217][217] & [224][224] - otherwise, as a consumer of both functions I would need to double-up on my own typing to handle each separately.
[217]: https://github.com/mylesj/immer/blob/7894ba364c75425eb11ef6dfb70bc1360147554e/src/types/types-external.ts#L217
[224]: https://github.com/mylesj/immer/blob/7894ba364c75425eb11ef6dfb70bc1360147554e/src/types/types-external.ts#L224
=> fix: consistent recipe return type in produceWithPatches

package.json
Some people have reported trouble with the new release of immer, in particular in #937 and #921. The reason seems to be that older build tools are having trouble to understand `.mjs` files as JavaScript.
Since currently immer publishes both an `.esm.js` and `.esm.mjs` bundle (introduced in #921), with the whole purpose of being backwards compatible, in this pull request I'm reverting the `module` and other fields in `package.json` to using the `.esm.js` bundle, while only the `exports` field uses the `.esm.mjs` bundle. I'm hoping that this will achieve both compatibility with Node.js as well as ancient build tools.
=> fix: Use .esm.js module for backwards compatibility with old build tools

package.json
This is required for TypeScript 4.7, otherwise it can't find the declaration file.
=> Add "types" to exports

website/i18n/zh-CN/docusaurus-plugin-content-docs/current/installation.mdx
I found the CDN script link was broken at installation docs in language zh_CN, which has redundant words because of trailing fullwidth period symbol, insert space can fix it.
=> docs: Fix broken cdn link due to trailing fullwidth period

src/core/immerClass.ts
Reading the source code, I came across an unused `arg3`. Seems like it initially threw an error if it was provided to guard against developers mistakenly passing in a patch listener, so basically unsupported from the beginning:
https://github.com/immerjs/immer/blame/ee1c977f5bf86e0f209e3df5f17bbc5bffb99dc3/src/immerClass.ts#L171
https://github.com/immerjs/immer/commit/86be737d8502aeb351296afe28ceb3e506a3a2ec#diff-3a3d78b97c1f27bfee63f1d6c1ca4e45d828fecfc6ed4ec7be92eea461639d6bR101
=> remove unused arg3 in produceWithPatches

__tests__/isDraftable.js, src/utils/common.ts
Edge case where constructor is not defined on an object, such as `Object.create(null)`.
=> protect against undefined constructor

src/types/types-external.ts
I got here looking at what the `Draft` type was in VS Code. This would have saved me a small amount of time parsing the type.
I did not spend long to add it and don't care to nitpick, so please just merge or close, no need to discuss :)
=> Add comment explaining Draft type

__tests__/base.js, src/core/proxy.ts
I suppose there is a bug in setter about ‘NaN’ special case.
=> fix: special case NaN in setter

src/types/types-external.ts
Minor typo fix for a produce function overload
=> chore: typo dormal -> normal

src/core/immerClass.ts
This PR updates the jsdoc parameter name "producer" to "recipe" to make the ide hints work again (currently broken)
=> fixed jsdoc parameter name

.vscode/settings.json
I formatted the code using the default TS formatter again in https://github.com/immerjs/immer/pull/1007
Adding this as a separate PR to help avoid this issue for everyone
=> chore: set vscode default formatter to prettier

__tests__/map-set.js, src/core/finalize.ts, src/utils/common.ts
As pointed out in #819 insertion order is not always preserved when adding to a Set, though according to MDN it should be.
We were already cloning and iterating over the cloned Set anyway in `finalize`.
If we take it a step further to clear the original Set after cloning and let `finalizeProperty` know it needs to re-add non-draftable children back to the target then we end up rebuilding the Set in it's original order.
We then no longer need to delete anything from the Set in `set`
=> [minor] Preserve insertion order of Sets, fixes #819

__tests__/base.js, __tests__/map-set.js
=> [minor] Add failing test for #819

src/core/immerClass.ts
do not freeze drafts used by nesting
[issue](https://github.com/immerjs/immer/issues/916)
=> [minor] fix:change tree structure level in nested patches

package.json
According to the typescript documentation: `Entry-point` for TypeScript resolution must occur first.
>Reference:  
> https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing
=> fix: ensure type exports is first

__performance_tests__/large-obj.js, __tests__/__prod_snapshots__/base.js.snap, __tests__/__snapshots__/base.js.snap, __tests__/base.js, __tests__/not-strict-copy.ts, package.json, src/core/current.ts, src/core/finalize.ts, src/core/immerClass.ts, src/core/proxy.ts, src/immer.ts, src/types/index.js.flow, src/utils/common.ts, website/docs/api.md, website/docs/complex-objects.md
Fixes #867
This PR improves the performance when updating the object that contains a large number of entries.
The current immer takes a long time for creating new object when the draft object has large amount of keys.
From some of the investigation, I found the cause that is `getOwnPropertyDescriptors` ([here](https://github.com/immerjs/immer/blob/master/src/utils/common.ts#L167)) .
In my computer, the `ownKeys` and its iteration don't take a long time but `getOwnPropertyDescriptors` takes time near the 10ms.
I can understand that the `getOwnPropertyDescriptors` is needed. Because immer should copy object's descriptors such as getter/setter/non-enumerable keys.
But some of the users doesn't need that strictness, I think.
~~Add the ability to opt-out of strict shallow copy implementation …
=> [breaking change] implement and default to useStrictShallowCopy, omitting getters

package.json
pre-published as immer@10.0.3-beta
=> fix: don't use `.mjs` file for react-native, which isn't supported by default. Fixes #1058 #1065

__tests__/base.js
I noticed that a possible regression was introduced with this change: https://github.com/immerjs/immer/commit/452a5085c0f84c3277ee16ab9b072ad99127ce90#diff-4ade25325a6cd7d1cca619364c84d19bfa47e6939a2c1b38d065767255b8f86eL68
The error is:
> TypeError: Cannot perform 'get' on a proxy that has been revoked
If you try this unit test on the commit before, it passes.
I don’t have enough context to know what the correct fix should be or whether this is working as intended, but I thought I’d at least demonstrate a failing unit test case.
=> Demonstrate possible regression

package.json
This will avoid breaking older tools that try to read `package.json` files from packages using package name instead of absolute path. 
Because when `exports` is set, accessing files that's not specified in the `exports` property is not allowed by node and it will throw a `ERR_PACKAGE_PATH_NOT_EXPORTED` error (rightly so).
This easily reproducible in the `node` repl.
This will throw 
```js
require.resolve('immer/package.json')
```
This will not throw
```js
require.resolve('./node_modules/immer/package.json')
```
Something similar has been mentioned in this great article https://blog.isquaredsoftware.com/2023/08/esm-modernization-lessons/#issue-history by @markerikson (_sorry for the ping, feel free to ignore_) when he worked on modernizing `@reduxjs/toolkit` (_which depends on `immer` and …
=> Add `./package.json` as an export entry

__tests__/not-strict-copy.ts, src/core/immerClass.ts, src/immer.ts, src/utils/common.ts, website/docs/complex-objects.md
=> feat: Make non-strict mode faster for classes. Addresses #1071

src/immer.ts
Related [issue](https://github.com/immerjs/immer/issues/1115)
=> Fix: export lost types

__tests__/base.js, __tests__/produce.ts, src/core/immerClass.ts, src/plugins/patches.ts, src/types/types-external.ts, src/utils/plugins.ts
My main goal is for `applyPatches` to accept `readonly Patch[]` as there is no reason why it shouldn't accept it. If you think that other changes here are too risky (like returning `readonly Patch[]` from `produceWithPatches`) then I can revert those bits of this change.
=> Make  `applyPatches` to accept  `readonly Patch[]`

src/utils/common.ts
Here's the current issue:
Fixes https://github.com/immerjs/immer/issues/1144 by prefacing the unused param with `_`.
=> Prefix param with underscore to prevent unused param warning

package.json
Fixes zustand immer dependency for react-native, where `enableMapSet()` wasn't caught by zustand
https://github.com/pmndrs/zustand/discussions/3211#discussioncomment-14115032
=> Update package.json exports for react-native

src/immer.ts
Consider an application that uses _only_ `produce` but no other methods. This PR allows such an application to be properly tree-shaken by a bundler, to eliminate the other exports altogether.
```ts
import { produce } from "immer";
const state = {
name: "A",
icon: "III",
accounts: [
{ address: "X", foo: "bax" },
{ address: "Y", foo: "bax" },
{ address: "Z", foo: "bax" },
],
};
const updateAccount = produce(
(draft: typeof state, newAccount: (typeof state)["accounts"][number]) => {
const accountIndex = draft.accounts.findIndex(
({ address }) => address === newAccount.address
);
if (accountIndex !== -1) {
draft.accounts[accountIndex].address = newAccount.address;
draft.accounts[accountIndex].foo = newAccount.foo;
}
}
);
const nextState = updateAccount(state, { address: "X", foo: "bar" }); …
```
=> fix: Mark exports as pure, for better tree-shakability

website/docs/update-patterns.md
Add an update pattern that explains how to replace & update objects in bulk through mutation, the docs felt like they could use a little more explanation
Kudos to @markerikson for offering guidance and input
=> chore: added update-pattern on how to replace & bulk update (nested) objects
